name: Build BadSuccessor (net461)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ibaiC/BadSuccessor
          fetch-depth: 1
          submodules: true

      # Needed for net461 reference assemblies
      - name: Install .NET Framework 4.6.1 Developer Pack
        run: choco install netfx-4.6.1-devpack -y --no-progress
        shell: powershell

      - name: Build with dotnet (Release)
        run: dotnet build .\BadSuccessor.sln -c Release

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: BadSuccessor-Release
          path: BadSuccessor\bin\Release\**
          if-no-files-found: error
